### ISSUE TITLE
When will VQ-Plenoxels and VQ-TensoRF available

### ISSUE THREAD

**Issue by AIBluefisher** [AlgoHunt/VQRF#1]
Hi, @AlgoHunt 

Thanks for your great work. As the current repo only contains VQ-DVGO, I'd like to know when will VQ-Plenoxels and VQ-TensoRF available or do you have any plans for this.

**Comment by jakobtroidl** [comment]
I am also curious if you plan to make the VQ-TensoRF implementation available @AlgoHunt.

**Comment by Spark001** [comment]
VQ-TensoRF is released in https://github.com/Spark001/VQ-TensoRF.
