### ISSUE TITLE
GPUs

### ISSUE THREAD

**Issue by triton99** [AlgoHunt/VQRF#6]
Thanks for sharing this great work! What kind of 8 GPUs do you use for training the model?

**Comment by AlgoHunt** [comment]
Hi, we use a 8x A100 GPU cloud machine to run our experiments

**Comment by triton99** [comment]
Thank you very much @AlgoHunt. Can I run it on RTX 8000 49GB or V100 16GB GPUs? And when will VQ-Plenoxels and VQ-TensoRF available?
